name: Cancel

on:
  workflow_run:
    workflows:
      - "CI"
      - "Docs"
    types:
      - requested

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.9.0
      with:
        # cancel itself and all later-scheduled workflows, leaving only the latest
        # helps if the pipeline is saturated
        all_but_latest: true
        workflow_id: ${{ github.event.workflow.id }}
